set(CTEST_CUSTOM_TESTS_IGNORE
        # googlebenchmark
        benchmark
        filter_simple
        filter_simple_list_only
        filter_simple_negative
        filter_simple_negative_list_only
        filter_suffix
        filter_suffix_list_only
        filter_suffix_negative
        filter_suffix_negative_list_only
        filter_regex_all
        filter_regex_all_list_only
        filter_regex_all_negative
        filter_regex_all_negative_list_only
        filter_regex_blank
        filter_regex_blank_list_only
        filter_regex_blank_negative
        filter_regex_blank_negative_list_only
        filter_regex_none
        filter_regex_none_list_only
        filter_regex_none_negative
        filter_regex_none_negative_list_only
        filter_regex_wildcard
        filter_regex_wildcard_list_only
        filter_regex_wildcard_negative
        filter_regex_wildcard_negative_list_only
        filter_regex_begin
        filter_regex_begin_list_only
        filter_regex_begin_negative
        filter_regex_begin_negative_list_only
        filter_regex_begin2
        filter_regex_begin2_list_only
        filter_regex_begin2_negative
        filter_regex_begin2_negative_list_only
        filter_regex_end
        filter_regex_end_list_only
        filter_regex_end_negative
        filter_regex_end_negative_list_only
        options_benchmarks
        basic_benchmark
        diagnostics_test
        skip_with_error_test
        donotoptimize_test
        fixture_test
        register_benchmark_test
        map_test
        multiple_ranges_test
        args_product_test
        link_main_test
        reporter_output_test
        templated_fixture_test
        user_counters_test
        internal_threading_test
        report_aggregates_only_test
        display_aggregates_only_test
        user_counters_tabular_test
        user_counters_thousands_test
        memory_manager_test
        cxx03
        complexity_benchmark
        benchmark_gtest
        benchmark_name_gtest
        commandlineflags_gtest
        statistics_gtest
        string_util_gtest
)
