name: Lint
on: [push]
jobs:
  dry-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check clang-format version
        run: |
          clang-format --version
      - name: Run clang-format
        run: |
          make lint
