name: Lint
on: [push]
jobs:
  dry-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check clang-format version
        run: |
          clang-format --version
      - name: Run clang-format
        run: |
          find . -regex '^\./\(src\|tests\|benchmark\)/.*\.\(cpp\|h\)$' -not -path './src/jsui/*' |
            xargs clang-format -i --dry-run --Werror
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install ESLint
        working-directory: ./src/jsui
        run: |
          npm install
      - name: Run ESLint
        working-directory: ./src/jsui
        run: |
          npx eslint src/
